---
title: "ADRECMO"
author: "Jolie Bruno, Antoine Kimmoun, Kevin Duarte, Feriel Azibani, Benjamin Deniaun"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    theme: journal
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
    latex_engine: pdflatex
  word_document: null
editor_options:
  chunk_output_type: console
always_allow_html: yes
---

```{=html}
<style type="text/css">

h1.title {
  font-size: 38px;
  text-align: center;
}
h4.author { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  text-align: center;
}
h4.date { /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  text-align: center;
}
</style>
```


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
# markdown options depending on the output (html with R code and Word without)
output <- knitr::opts_knit$get("rmarkdown.pandoc.to")
if (output=="html") knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = TRUE, comment = "", fig.align = "center", fig.width= 17, fig.asp =0.70, out.width = "90%")
if (output=="docx") knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE, comment = "", fig.align = "center", fig.width= 17, fig.asp =0.70, out.width = "90%")
if (output=="pdf") knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE, comment = "", fig.align = "center", fig.width= 17, fig.asp =0.70, out.width = "90%")
options(max.print = .Machine$integer.max)
```

# Packages needed

```{r,include=FALSE}
library(dplyr)
library(lubridate)
library(gtsummary)
library(readr)
library(ggplot2)
library(tableone)
library(flextable)
library(sjlabelled)
library(readxl)
library(stringr)
library(tidyr)
library(purrr)
library(tableone)
library(dplyr)
library(naniar)
library(tidyr)
```

# Fonctions

```{r,include=FALSE}
source("FUNCTIONS/Examples - RCS effect + interaction cont x factor + check normality 181224.R")
```

# DATA Load

```{r,include=FALSE}
fichier <- "DATA/df_i_stabilized.xlsx"
feuilles <- excel_sheets(fichier)
data_list <- lapply(feuilles, function(feuille) {
  read_excel(fichier, sheet = feuille)
})


ADR1 <- data_list[[1]] %>%
  select( "Patient","Jour", "%Total")%>%
  filter(!is.na(`%Total`))%>%
  rename(value = `%Total`)%>%
  mutate(ID =str_replace(Patient, "Patient (\\d+) (\\w+)", "\\1-\\2"))%>%
  pivot_wider(
    names_from = "Jour",
     names_prefix = "ADR1_",
    values_from = "value",
    values_fn = mean,  # Moyenne des doublons
    values_fill = NA
  )%>%
  mutate (`ADR1_J3-5` = case_when(is.na(`ADR1_J3-5`)&!is.na(ADR1_J5)~ADR1_J5,
                             T~`ADR1_J3-5`),
          ADR1_JS = case_when(is.na(ADR1_JS)&!is.na(`ADR1_J3-5-S`)~`ADR1_J3-5-S`,
                             T~ADR1_JS))%>%
  rename(ADR1_J3_J5=`ADR1_J3-5`)%>%
  
  dplyr::select(ID,
                ADR1_J0,
                ADR1_J3_J5,
                ADR1_JS)


ADR2 <- data_list[[2]] %>%
  select( "Patient","Jour", "%Total")%>%
  filter(!is.na(`%Total`))%>%
  rename(value = `%Total`)%>%
  mutate(ID = str_replace(Patient, "Patient (\\d+) (\\w+)", "\\1-\\2"))%>%
  pivot_wider(
    names_from = "Jour",
    values_from = "value",
     names_prefix = "ADR2_" ,
    values_fn = mean,  # Moyenne des doublons
    values_fill = NA
  )%>%
  mutate (
          ADR2_JS = case_when(is.na(ADR2_JS)&!is.na(`ADR2_J3-5-S`)~`ADR2_J3-5-S`,
                             T~ADR2_JS))%>%
  rename(ADR2_J3_J5=`ADR2_J3-5`)%>%
  dplyr::select(ID,
                ADR2_J0,
                ADR2_J3_J5,
                ADR2_JS)


  #Chercher doublons
ADR1%>%
  group_by(Patient, ID, Jour) %>%
  summarise(n = n(), .groups = "drop") %>%
  filter(n > 1)
ADR2%>%
  group_by(Patient, ID, Jour) %>%
  summarise(n = n(), .groups = "drop") %>%
  filter(n > 1)

##Error in `group_by()`:
#Column `Patient` is not found.
#Column `Jour` is not found.

colnames(ADR1) # no Patient or Jour
colnames(ADR2)

str(ADR1)
str(ADR2)


DATA <- read_delim("DATA/ADRECMO_DATA.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)%>%
  mutate(nom = str_to_upper(nom),
         prenom =str_to_upper(prenom),
         ID = paste0(numero,"-",nom,prenom))
        
df_list <- lst(DATA,ADR1,ADR2)

df <- reduce(df_list, left_join, by="ID")

```

# DATA Managment

```{r,include=FALSE}

df <- df %>%
  mutate(
    Temp_D0 = round(Temp_D0, 1),
    Age = as.numeric(Age),
    Gender = case_when(
      Gender == 0 ~ "Men",
      Gender == 1 ~ "Women",
      TRUE ~ as.character(Gender)
    ),
    Outcome = case_when(
      Outcome == 1 ~ "ECMO Weaning",
      Outcome == 2 ~ "Bridge to Transplant",
      Outcome == 3 ~ "Bridge to LVAD",
      Outcome == 4 ~ "Death",
      TRUE ~ as.character(Outcome)
    ),
    Pulsepressure_D0 = PAS_D0 - PAD_D0,
    icu_admiss_date = dmy(icu_admiss_date),
    icu_discharge_date = dmy(icu_discharge_date),
    ecmo_start_date = dmy(ecmo_start_date),
    ecmo_stop_date = dmy(ecmo_stop_date),
    Time_hosp = as.numeric(icu_discharge_date - icu_admiss_date),
    Time_ecmo = as.numeric(ecmo_stop_date - ecmo_start_date)
  )

```

# Check for normality 

```{r,include=FALSE}

for (var in var.cont) {
  if (var %in% colnames(T1)) {
    print(
      ggplot(T1, aes_string(var)) +
        geom_histogram(bins = 15, fill = "blue", alpha = 0.5) +
        ggtitle(paste("Distribuzione di", var))
    )
  } else {
    message(paste("❌ Variabile", var, "non trovata in T1"))
  }
}

```

# TABLE 1: description of baseline characteristics of the population at inclusion

```{r,include=FALSE}

var.cat <- c("Gender", "HTN", "DM", "Immunodepression", "CKD", "Neurologic_deficit", "Chronic_respiratory_disease", "HF", "Cardiac_arrest_before_canul", "IABP_D0", "Intubation", "EER_D0", "Outcome", "Betablocker", "Alphablocker", "Levosimendan", "Death")

var.cont <- c("Age", "BMI", "PAS_D0", "PAD_D0", "PAM_D0", "Pulsepressure_D0", "HR_D0", "Temp_D0", "Preecmo_tte_ef", "Preecmo_tte_vtiao", "Preecmo_tte_diam_LV", "Preecmo_tte_tapse", "Preecmo_tte_vmax_s_mit_lat_LV", "NADcum_D0", "DOBUcum_D0", "pH_D0", "Sao2_D0", "Paco2_D0", "Lact_D0", "Hco3_D0", "Creat_D0", "Urea_D0", "ALAT_D0", "ASAT_D0", "Bili_D0", "PT_D0", "Tropo_i_hs_D0", "Ntprobnp_D0", "DPP3_D0", "Plq_D0","ADRtot_D0","ADRtot_D3", "ADRtot_w", "Lenght_eer", "Lenght_vm", "Time_hosp", "Time_ecmo")

var.tot <- c(var.cat, var.cont)

T1 <- df %>%
  dplyr::select(all_of(var.tot))%>%
  mutate(across(all_of(var.cont), as.numeric), 
         across(all_of(var.cat), as.factor))


## Table 1 standard

table1 <- CreateTableOne(vars = var.tot, factorVars = var.cat, data =T1) # sans groupe de strata

table1 <- print(table1, nonnormal =var.cont)

table1_df <- as.data.frame(print(table1, nonnormal = var.cont, showAllLevels = TRUE))
table1_df$Variables <- row.names(table1_df)

row.names(table1_df)<-NULL
table1_df <- table1_df[, c(2,1)]

T1_n <- T1%>%
  summarise(across(everything(), ~ sum(is.na(.))))%>%
  pivot_longer(cols= everything(),
    values_to = "n_missing",
    names_to = "ID")%>%
  mutate(n_missing = paste0(n_missing,"/50"),
         ID = trimws(ID))

table1_df1 <- table1_df %>%
  mutate(ID = sub("\\(median \\[IQR\\]\\)|= 1 \\(\\%\\)|= Women \\(\\%\\)|\\(\\%\\)", "",Variables),
         ID = trimws(ID))

table_1_vf <- left_join(table1_df1,T1_n, by="ID")%>%
  select(Variables,n_missing,Overall)%>%
  mutate(n_missing = replace_na(n_missing,""))

table_1_vf <- left_join(table1_df1, T1_n, by = "ID") %>%
  mutate(N = 50 - as.numeric(sub("/50", "", replace_na(n_missing, "0")))) %>%  # Calcola N
  select(Variables, N, Overall)  

print(table_1_vf)

```

#Figure 1: Association between ADRB expressions and outcomes

```{r,include=FALSE}

## ADRB1 (J0, J3-5, JS) ~ death

df_long <- df %>%
  pivot_longer(
    cols = c(ADR1_J0, ADR1_J3_J5, ADR1_JS), 
    names_to = "ADR1_time", 
    values_to = "value"
  ) %>%
  mutate(j90_deces = factor(j90_deces, levels = c(0, 1), labels = c("NO", "YES")))  


count_data <- df_long %>%
  filter(!is.na(value))%>%
  group_by(ADR1_time, j90_deces) %>%
  summarise(n = n(), .groups = "drop")%>%
  filter(!is.na(j90_deces))

#Boxplot

ggplot(df_long |> filter(!is.na(ADR1_time)), aes(x = ADR1_time, y = value, fill = j90_deces)) +
  geom_boxplot(position = position_dodge(0.7), width = 0.6) +  
  scale_y_log10() +  
  labs(
    x = "ADR1_time",
    y = "Value",
    title = "Boxplots ADR1 ~ Death"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("NO" = "#1f78b4", "YES" = "#e31a1c"))+
  geom_text(data = count_data, aes(x = ADR1_time, y = min(df_long$value, na.rm = TRUE) * 0.8, 
                                   label = paste0("n=", n), group = j90_deces), 
            position = position_dodge(0.7), size = 4, vjust = 1)

ggsave("Figures/boxplot_ADR1_Death.pdf", width = 8, height = 6)


## ADRB2 (J0, J3-5, JS) ~ death

#
df_long <- df %>%
  select(ID,ADR2_J0, ADR2_J3_J5, ADR2_JS,j90_deces)%>%
  pivot_longer(
    cols = c(ADR2_J0, ADR2_J3_J5, ADR2_JS), 
    names_to = "ADR2_time", 
    values_to = "value"
  ) %>%
  mutate(j90_deces = factor(j90_deces, levels = c(0, 1), labels = c("NO", "YES")))  

count_data <- df_long %>%
  filter(!is.na(value))%>%
  group_by(ADR2_time, j90_deces) %>%
  summarise(n = n(), .groups = "drop")%>%
  filter(!is.na(j90_deces))

#Boxplot

ggplot(df_long |> filter(!is.na(ADR2_time)), aes(x = ADR2_time, y = value, fill = j90_deces)) +
  geom_boxplot(position = position_dodge(0.7), width = 0.6) +  
  scale_y_log10() +  
  labs(
    x = "ADR2_time",
    y = "Value",
    title = "Boxplots ADR2 ~ Death"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("NO" = "#1f78b4", "YES" = "#e31a1c"))  +
  geom_text(data = count_data, aes(x = ADR2_time, y = min(df_long$value, na.rm = TRUE) * 0.8, 
                                   label = paste0("n=", n), group = j90_deces), 
            position = position_dodge(0.7), size = 4, vjust = 1)

ggsave("Figures/boxplot_ADR2_Death.pdf", width = 8, height = 6)

##With composite outcome

df_long <- df %>%
  select(ID,ADR1_J0, ADR1_J3_J5, ADR1_JS, Outcome)%>%
  mutate(Outcome1 = case_when(Outcome=="Bridge to LVAD"|Outcome=="Bridge to Transplant"~ "Bridge to transplant or LVAD",T~Outcome))%>%
  pivot_longer(
    cols = c(ADR1_J0, ADR1_J3_J5, ADR1_JS), 
    names_to = "ADR1_time", 
    values_to = "value"
  )


count_data <- df_long %>%
  filter(!is.na(value))%>%
  group_by(ADR1_time, Outcome1) %>%
  summarise(n = n(), .groups = "drop")%>%
  filter(!is.na(Outcome1))

#Boxplot

ggplot(df_long |> filter(!is.na(ADR1_time)), aes(x = ADR1_time, y = value, fill = Outcome1)) +
  geom_boxplot(position = position_dodge(0.7), width = 0.6) +  
  scale_y_log10() +  
  labs(
    x = "ADR1_time",
    y = "Value",
    title = "Boxplots ADR1 ~ Outcome"
  ) +
  geom_text(data = count_data, aes(x = ADR1_time, y = min(df_long$value, na.rm = TRUE) * 0.8, 
                                   label = paste0("n=", n), group = Outcome1), 
            position = position_dodge(0.7), size = 4, vjust = 1)


ggsave("Figures/boxplot_ADR1_Outcome.pdf", width = 8, height = 6)


## ADRB2 (J0, J3-5, JS) ~ death

df_long <- df %>%
  select(ID,ADR2_J0, ADR2_J3_J5, ADR2_JS, Outcome)%>%
  mutate(Outcome1 = case_when(Outcome=="Bridge to LVAD"|Outcome=="Bridge to Transplant"~ "Bridge to transplant or LVAD",T~Outcome))%>%
  pivot_longer(
    cols = c(ADR2_J0, ADR2_J3_J5, ADR2_JS), 
    names_to = "ADR2_time", 
    values_to = "value"
  )


count_data <- df_long %>%
  filter(!is.na(value))%>%
  group_by(ADR2_time, Outcome1) %>%
  summarise(n = n(), .groups = "drop")%>%
  filter(!is.na(Outcome1))

#Boxplot

ggplot(df_long |> filter(!is.na(ADR2_time)), aes(x = ADR2_time, y = value, fill = Outcome1)) +
  geom_boxplot(position = position_dodge(0.7), width = 0.6) +  
  scale_y_log10() +  
  labs(
    x = "ADR2_time",
    y = "Value",
    title = "Boxplots ADR2 ~ Outcome"
  ) +
  geom_text(data = count_data, aes(x = ADR2_time, y = min(df_long$value, na.rm = TRUE) * 0.8, 
                                   label = paste0("n=", n), group = Outcome1), 
            position = position_dodge(0.7), size = 4, vjust = 1)


ggsave("Figures/boxplot_ADR2_Outcome.pdf", width = 8, height = 6)

```

#Figure 2: Association between VTI and weaning

```{r,include=FALSE}

# VTI at weaning, 3L vs 1.5 L

colnames(df) <- gsub(",", ".", colnames(df))  

df_long_unique <- df_long %>%
  distinct(ID, ECMO_Weaning, .keep_all = TRUE)

table(df_long_unique$ECMO_Weaning)


df_long_unique <- df %>%
  pivot_longer(
    cols = c(jsev_epr_sev_t0_3l_itv, jsev_epr_sev_t1_1.5l_itv), 
    names_to = "VTI_weaning", 
    values_to = "value"
  ) %>%
  mutate(ECMO_Weaning = case_when(
    Outcome == "ECMO Weaning" ~ "YES",  
    Outcome != "ECMO Weaning" ~ "NO"    
  )) %>%
  mutate(ECMO_Weaning = factor(ECMO_Weaning, levels = c("NO", "YES")))  

count_data <- df_long_unique %>%
  filter(!is.na(value))%>%
  group_by(VTI_weaning, ECMO_Weaning) %>%
  summarise(n = n(), .groups = "drop")%>%
  filter(!is.na(ECMO_Weaning))

#Boxplot

ggplot(df_long_unique |> filter(!is.na(VTI_weaning)), aes(x = VTI_weaning, y = value, fill = ECMO_Weaning)) +
  geom_boxplot(position = position_dodge(0.7), width = 0.6) +  
  scale_y_log10() +  
  labs(
    x = "VTI_weaning",
    y = "Value",
    title = "Boxplots VTI at weaning ~ Success of Weaning"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("NO" = "#984ea3", "YES" = "#4daf4a"))+
  geom_text(data = count_data, aes(x = VTI_weaning, y = min(df_long$value, na.rm = TRUE) * 0.8, 
                                   label = paste0("n=", n), group = ECMO_Weaning), 
            position = position_dodge(0.7), size = 4, vjust = 1)

ggsave("Figures/boxplot_VTI_Weaning.pdf", width = 8, height = 6)


## ECMO Weaning is  NO 28 and YES 21. In Figure not same n!!!

# Figure shows that in ECMO Weaning VTI in higher and raises from 3l -> 1.5 L (results just for reassuring)

```

Figure 3: Association between ADRB expressions and weaning

```{r,include=FALSE}

# VTI at weaning, 1.5 L and ADR1

colnames(df) <- gsub(",", ".", colnames(df)) 

df_long <- df %>%
  pivot_longer(
    cols = c(ADR1_JS, jsev_epr_sev_t1_1.5l_itv),  
    names_to = "Variable", 
    values_to = "Value"
  ) %>%
  mutate(ECMO_Weaning = case_when(
    Outcome == "ECMO Weaning" ~ "YES",
    TRUE ~ "NO"
  )) %>%
  mutate(ECMO_Weaning = factor(ECMO_Weaning, levels = c("NO", "YES")))

count_data <- df_long %>%
  filter(!is.na(Value)) %>%
  group_by(Variable, ECMO_Weaning) %>%
  summarise(n = n(), .groups = "drop")

# Boxplot
ggplot(df_long, aes(x = Variable, y = Value, fill = ECMO_Weaning)) +
  geom_boxplot(position = position_dodge(0.7), width = 0.6) +
  labs(
    x = "Variable",
    y = "Value",
    title = "ADR1_JS and VTI at 1.5L ~ Weaning"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("NO" = "#ffcc00", "YES" = "#ff6600")) +
  geom_text(data = count_data, aes(x = Variable, y = min(df_long$Value, na.rm = TRUE) * 0.8, 
                                   label = paste0("n=", n), group = ECMO_Weaning), 
            position = position_dodge(0.7), size = 4, vjust = 1)


ggsave("Figures/boxplot_ADR1_Weaning.pdf", width = 8, height = 6)

# VTI at weaning, 1.5 L and ADR2

colnames(df) <- gsub(",", ".", colnames(df)) 

df_long <- df %>%
  pivot_longer(
    cols = c(ADR2_JS, jsev_epr_sev_t1_1.5l_itv),  
    names_to = "Variable", 
    values_to = "Value"
  ) %>%
  mutate(ECMO_Weaning = case_when(
    Outcome == "ECMO Weaning" ~ "YES",
    TRUE ~ "NO"
  )) %>%
  mutate(ECMO_Weaning = factor(ECMO_Weaning, levels = c("NO", "YES")))

count_data <- df_long %>%
  filter(!is.na(Value)) %>%
  group_by(Variable, ECMO_Weaning) %>%
  summarise(n = n(), .groups = "drop")

# Boxplot
ggplot(df_long, aes(x = Variable, y = Value, fill = ECMO_Weaning)) +
  geom_boxplot(position = position_dodge(0.7), width = 0.6) +
  labs(
    x = "Variable",
    y = "Value",
    title = "ADR2_JS and VTI at 1.5L ~ Weaning"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("NO" = "#ffcc00", "YES" = "#ff6600")) +
  geom_text(data = count_data, aes(x = Variable, y = min(df_long$Value, na.rm = TRUE) * 0.8, 
                                   label = paste0("n=", n), group = ECMO_Weaning), 
            position = position_dodge(0.7), size = 4, vjust = 1)


ggsave("Figures/boxplot_ADR2_Weaning.pdf", width = 8, height = 6)

```

# Statistic analisys

```{r,include=FALSE}

### ADR1

##To verify the relationship between ADR1_JS and Weaning (YES/NO) → Wilcoxon test

wilcox.test(ADR1_JS ~ ECMO_Weaning, data = df_long)

#p-value = 0.9342 --> R says exact p value not possible

wilcox.test(ADR1_JS ~ ECMO_Weaning, data = df_long, exact = FALSE, correct = FALSE)

#p-value = 0.9248

##To quantify the correlation between a continuous and a binary variable → Spearman test

cor.test(df_long$ADR1_JS, as.numeric(df_long$ECMO_Weaning), method = "spearman")

#rho = 0.0144, p-value = 0.9261

### ADR2 (I had to use df_long_unique!!)

#p-value = 0.2088

wilcox.test(ADR2_JS ~ ECMO_Weaning, data = df_long_unique)

cor.test(df_long_unique$ADR2_JS, as.numeric(df_long$ECMO_Weaning), method = "spearman")

# rho=0.1934453, p-value = 0.2083

```

# Survival ~ ADR

```{r,include=FALSE}


```