---
title: "ADRECMO"
author: "Jolie Bruno, Antoine Kimmoun, Kevin Duarte, Feriel Azibani, Benjamin Deniaun"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    theme: journal
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
    latex_engine: pdflatex
  word_document: null
editor_options:
  chunk_output_type: console
always_allow_html: yes
---

# Libraries

```{r,include=FALSE}

options(repos = c(CRAN = "https://cran.r-project.org"))

install.packages("cardx")

library(dplyr)
library(lubridate)
library(gtsummary)
library(readr)
library(ggplot2)
library(tableone)

```

# Load DATA

```{r,include=FALSE}

DATA <- read_delim("DATA/ADRECMO_DATA.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)

```

# LOAD FUNCTIONS

```{r,include=FALSE}

```

# DATA MANAGEMENT

```{r,include=FALSE}

DATA <- DATA %>%
  mutate(
    Temp_D0 = round(Temp_D0, 1),
    BNP_D0 = as.numeric(BNP_D0),
    Age = as.numeric(Age),
    Gender = case_when(
      Gender == 0 ~ "Men",
      Gender == 1 ~ "Women",
      TRUE ~ as.character(Gender)
    ),
    Outcome = case_when(
      Outcome == 1 ~ "ECMO Weaning",
      Outcome == 2 ~ "Bridge to Transplant",
      Outcome == 3 ~ "Bridge to LVAD",
      Outcome == 4 ~ "Death",
      TRUE ~ as.character(Outcome)
    ),
    Pulsepressure_D0 = PAS_D0 - PAD_D0,
    icu_admiss_date = dmy(icu_admiss_date),
    icu_discharge_date = dmy(icu_discharge_date),
    ecmo_start_date = dmy(ecmo_start_date),
    ecmo_stop_date = dmy(ecmo_stop_date),
    Time_hosp = as.numeric(icu_discharge_date - icu_admiss_date),
    Time_ecmo = as.numeric(ecmo_stop_date - ecmo_start_date)
  )

# Median DPP3
median_DPP3 <- median(DATA$DPP3_D0, na.rm = TRUE)
print(median_DPP3)
# 72.9

# Quantil DPP3 
Q_DPP3 <- quantile(DATA$DPP3_D0, probs = c(0.25, 0.5, 0.75), na.rm = TRUE)
print(Q_DPP3)

## In the literature normal DPP3 40 ng/ml. Could we separate our population in two group low vs high DPP3 (i.e. Q1 (<50) vs Q2-4 (>50)) as meaningful (near normal) cut point? Better Q2 for numerosity of the group? In OptimaCC 59.1 (Q3) was cutoff. In CARD Schock 33.4 (Q2)

# DPP3 quantile
Q_DPP3 <- quantile(DATA$DPP3_D0, probs = c(0.25, 0.5, 0.75), na.rm = TRUE)

##  25%   50%   75% 
##  50.0  72.9 164.1 

DATA <- DATA %>%
  mutate(
    DPP3_quartile = case_when(
      DPP3_D0 <= Q_DPP3[1] ~ "Q1",
      DPP3_D0 > Q_DPP3[1] & DPP3_D0 <= Q_DPP3[2] ~ "Q2",
      DPP3_D0 > Q_DPP3[2] & DPP3_D0 <= Q_DPP3[3] ~ "Q3",
      TRUE ~ "Q4"
    ),
    DPP3_group = case_when(
      DPP3_D0 <= Q_DPP3[1] ~ "Q1",
      TRUE ~ "Q2+Q3+Q4"
    )
  )

```

# TABLE 1. Description of the population included

```{r,include=FALSE}



var.cat <-c("mettre ici les variables categorielle")

var.cont <- c("mettre ici les variables continues")

var.tot <- c(var.cat, var.cont)


T1 <- data%>%
  dplyr::select(all_of(var.tot))%>%
  mutate(across(var.cont, as.numeric),
         across(var.car, as.factor))

#verifier la normalité des variables


table1 <- CreateTableOne(vars = var.tot, factorVars = var.cat,)


# ~ DPP3 Quantile

Table_1 <- DATA |> 
  select(Age, Gender, HTN, DM, Immunodepression, CKD, Neurologic_deficit, 
         Chronic_respiratory_disease, HF, Cardiac_arrest_before_canul, 
         Intubation, EER_D0, PAS_D0, PAD_D0, PAM_D0, Pulsepressure_D0, 
         HR_D0, Temp_D0, IABP_D0, Preecmo_tte_ef, Preecmo_tte_vtiao, 
         NADcum_D0, DOBUcum_D0, pH_D0, Sao2_D0, Paco2_D0, Lact_D0, 
         Hco3_D0, Creat_D0, ALAT_D0, ASAT_D0, Bili_D0, Tropo_i_hs_D0, 
         BNP_D0, Ntprobnp_D0, DPP3_group, Time_hosp, Time_ecmo, Outcome) |> 
  tbl_summary(
    by = DPP3_group, 
    missing = "no",
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",  
      all_categorical() ~ "{n} ({p}%)"    
    )
  ) |> 
  add_p() |>      
  add_overall() |> 
  add_n()          

Table_1

## I can't correct BNP as mean

# ~ death

Table_2 <- DATA |> 
  select(Age, Gender, HTN, DM, Immunodepression, CKD, Neurologic_deficit, Chronic_respiratory_disease, 
         HF, Cardiac_arrest_before_canul, Intubation, EER_D0, PAS_D0, PAD_D0, PAM_D0, Pulsepressure_D0, 
         HR_D0, Temp_D0, IABP_D0, Preecmo_tte_ef, Preecmo_tte_vtiao, 
         NADcum_D0, DOBUcum_D0, pH_D0, Sao2_D0, Paco2_D0, Lact_D0, 
         Hco3_D0, Creat_D0, ALAT_D0, ASAT_D0, Bili_D0, Tropo_i_hs_D0, 
         BNP_D0, Ntprobnp_D0, DPP3_D0, Death, Time_hosp, Time_ecmo) |> 
  tbl_summary(by = Death, missing = "no") |> 
  add_p() |> 
  add_overall() |> 
  add_n()           

Table_2

## same for BNP and I don't understand why Time_hosp and Time_ecmo here are NA

```

# Distribuition of some variables

```{r,include=FALSE}

plot <- ggplot(DATA, aes(x = DPP3_D0)) +
  geom_density(alpha = 0.5, fill = "blue") +
  labs(title = paste("Density plot DPP3"),
       x = "DPP3", y = "Density") +
  theme_minimal()

plot_vti <- ggplot(DATA, aes(x = Preecmo_tte_vtiao)) +
  geom_density(alpha = 0.5, fill = "blue") +
  labs(title = paste("Density plot VTI preecmo"),
       x = "Preecmo_tte_vtiao", y = "Density") +
  theme_minimal()

plot_ef <- ggplot(DATA, aes(x = Preecmo_tte_ef)) +
  geom_density(alpha = 0.5, fill = "blue") +
  labs(title = paste("Density plot preecmo LVEF"),
       x = "Preecmo_tte_ef", y = "Density") +
  theme_minimal()

plot_lact <- ggplot(DATA, aes(x = Lact_D0)) +
  geom_density(alpha = 0.5, fill = "blue") +
  labs(title = paste("Density plot Lactat_D0"),
       x = "Lact_D0", y = "Density") +
  theme_minimal()

plot_pp <- ggplot(DATA, aes(x = Pulsepressure_D0)) +
  geom_density(alpha = 0.5, fill = "blue") +
  labs(title = paste("Density plot PP_D0"),
       x = "Pulsepressure_D0", y = "Density") +
  theme_minimal()

print(plot)
print(plot_vti)
print(plot_lact)
print(plot_ef)
print(plot_pp)

```
